exclude: '^docs/|/migrations/|devcontainer.json|^tests/'
default_stages: [commit]

default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: check-added-large-files
      - id: debug-statements
      - id: requirements-txt-fixer

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        files: ^compose/.*\.(yaml|yml)$
        types: [yaml]
        args: [-c=.yamllint.yaml]

  - repo: https://github.com/adamchainz/django-upgrade
    rev: 1.22.2
    hooks:
      - id: django-upgrade
        args: [--target-version, "5.0"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.2
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format
        exclude: "frontend/.*|.*\\.html$"

  - repo: https://github.com/Riverside-Healthcare/djLint
    rev: v1.36.4
    hooks:
      - id: djlint-reformat-django
        types: [html]
      - id: djlint-django
        types: [html]

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v9.18.0
    hooks:
      - id: eslint
        files: \.(js|ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - "@typescript-eslint/parser@5.62.0"
          - "@typescript-eslint/eslint-plugin@5.62.0"
          - "typescript@5.0.4"
          - "eslint-plugin-react@7.33.2"
          - "eslint-plugin-react-hooks@4.6.0"
          - "eslint-config-react-app@7.0.1"
          - "eslint-plugin-import@2.29.1"
          - "eslint-plugin-jsx-a11y@6.8.0"
          - "eslint-plugin-testing-library@6.2.0"
          - "eslint-plugin-jest@27.6.1"
        args:
          - --config
          - frontend/.eslintrc.json
          - --fix

  - repo: https://github.com/PyCQA/bandit
    rev: 1.8.2
    hooks:
      - id: bandit
        args: ["-c", "pyproject.toml"]
        additional_dependencies: ["bandit[toml]"]

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py312-plus]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [javascript, jsx, ts, tsx, css, scss, json]
        exclude: ".*\\.py$"
        additional_dependencies:
          - prettier@3.1.0

# sets up .pre-commit-ci.yaml to ensure pre-commit dependencies stay up to date
ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false