# Generated by Django 5.1.5 on 2025-01-29 21:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChainExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('chain_type', models.CharField(max_length=100)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'indexes': [models.Index(fields=['chain_type'], name='django_llm__chain_t_d10ef8_idx'), models.Index(fields=['status'], name='django_llm__status_a1e1cb_idx'), models.Index(fields=['started_at'], name='django_llm__started_6feebb_idx')],
            },
        ),
        migrations.CreateModel(
            name='ChainStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('input_data', models.JSONField(default=dict)),
                ('output_data', models.JSONField(default=dict, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('chain_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='django_llm.chainexecution')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LLMProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Provider identifier (e.g., 'anthropic')", max_length=50, unique=True)),
                ('model', models.CharField(help_text="Model identifier (e.g., 'claude-3-sonnet-20240229')", max_length=100)),
                ('api_key', models.CharField(help_text='API key for provider authentication', max_length=255)),
                ('max_tokens', models.IntegerField(default=1024, help_text='Maximum tokens for response generation')),
                ('temperature', models.FloatField(default=0.7, help_text='Sampling temperature for response generation')),
                ('config', models.JSONField(default=dict, help_text='Additional provider-specific configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this provider configuration is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'LLM Provider',
                'verbose_name_plural': 'LLM Providers',
                'indexes': [models.Index(fields=['name'], name='django_llm__name_c4cdda_idx'), models.Index(fields=['is_active'], name='django_llm__is_acti_87215a_idx')],
            },
        ),
        migrations.CreateModel(
            name='StoredArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chain_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='django_llm.chainexecution')),
                ('step', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artifacts', to='django_llm.chainstep')),
            ],
        ),
        migrations.CreateModel(
            name='TokenUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('prompt_tokens', models.IntegerField()),
                ('completion_tokens', models.IntegerField()),
                ('total_tokens', models.IntegerField()),
                ('estimated_cost', models.DecimalField(decimal_places=6, max_digits=10, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chain_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token_usage', to='django_llm.chainstep')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usage_logs', to='django_llm.llmprovider')),
            ],
        ),
        migrations.AddIndex(
            model_name='chainstep',
            index=models.Index(fields=['step_type'], name='django_llm__step_ty_fc3433_idx'),
        ),
        migrations.AddIndex(
            model_name='chainstep',
            index=models.Index(fields=['started_at'], name='django_llm__started_b4cd48_idx'),
        ),
        migrations.AddIndex(
            model_name='storedartifact',
            index=models.Index(fields=['name'], name='django_llm__name_bc0751_idx'),
        ),
        migrations.AddIndex(
            model_name='storedartifact',
            index=models.Index(fields=['created_at'], name='django_llm__created_369dd0_idx'),
        ),
        migrations.AddIndex(
            model_name='tokenusagelog',
            index=models.Index(fields=['timestamp'], name='django_llm__timesta_183374_idx'),
        ),
    ]
